### PR TITLE
Fix Schematic Print

### PR DESCRIPTION
**Pull request by fantahund**

### CODE REVIEW

**Comment by Stacxzzzz** [comment]
Im sorry, i am not crazy smart with this yet, but I hope to get better. How do I change my files to be fixed like yours?

**Comment by fantahund** [comment]
You have to clone my reposetory. and just build it with "./gradew build" in the console

**Comment by fantahund** [comment]
If it doesn't work, let me know and I can send it to you.

**Comment by Stacxzzzz** [comment]
> You have to clone my reposetory. and just build it with "./gradew build" in the console

It says I need a url that is pretty much "https://svn.example.org/code/svn" is that where i am supposed to be?

**Comment by fantahund** [comment]
no. but wait i'll just send you the jar. https://fantacs.de/litematica-fabric-1.19-0.11.2.jar

**Comment by Stacxzzzz** [comment]
> no. but wait i'll just send you the jar. https://fantacs.de/litematica-fabric-1.19-0.11.2.jar
Wow man, it works great for me now! thanks for the help.

**Pull request merged**
